spring:
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: INFO
    org.springframework.jdbc.core: DEBUG     # JDBC 로그
    org.mybatis: DEBUG                       # MyBatis 사용 시
    org.apache.ibatis: DEBUG